language: generic
sudo: false
matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - gfortran
            - cmake
              # math libraries
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libopenblas-base
            - libopenblas-dev

    - os: osx
      osx_image: xcode10.2
      compiler: gcc
      env: SOURCES=homebrew
      
 env:
        - PWD=`pwd`

before_install:
        - mkdir gauopen
        - mkdir mqc-install
        - cd gauopen
        - wget http://gaussian.com/g16/gauopen_v2.zip
        - unzip gauopen_v2.zip
        - ls
        - cd ..
        - pwd
        - ls
        - echo "pwd is $PWD"

install: ./mqc_install  <<< $'y\nG\n./mqc-install\n-lblas\n-llapack\n./gauopen\ny\ng16\n'

