language: generic
sudo: false
matrix:
  include:

    - os: linux
      compiler: gcc
      env: SOURCES=ubuntu-toolchain-r-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - gfortran
            - cmake
              # math libraries
            - libblas-dev
            - liblapack-dev
            - libatlas-base-dev
            - libopenblas-base
            - libopenblas-dev

    - os: osx
      osx_image: xcode10.2
      compiler: gcc
      env: SOURCES=homebrew

before_install:
        - mkdir gauopen
        - mkdir mqc-install
        - cd gauopen
        - wget http://gaussian.com/g16/gauopen_v2.zip
        - unzip gauopen_v2.zip
        - cd ..
        - ls
        - autoreconf -f -i

install: echo -e "y\nG\n$TRAVIS_BUILD_DIR/mqc-install\n-lblas\n-llapack\n$TRAVIS_BUILD_DIR/gauopen\ny\ng16\n" | ./mqc_install 

